### ISSUE TITLE
Render Error

### ISSUE THREAD

**Issue by CredenceHamby** [Jericho1060/DU-Mining-Units-Monitoring#1]
Isn't giving the "No mining unit detected" but rather a render script error. Once this happens, I'm having to re paste the entire LUA to get it fixed.

**Comment by CredenceHamby** [comment]
Seems like it's doing this when a Mu is hooked up, but haven't been turned on yet...

**Comment by thoda-dev** [comment]
Confirmed, there is a bug when a mining units has never been started getting the ore pool of the map, I still have to investigate a bit more about what's going wrong with it, but i should be able to manage it.

**Comment by CredenceHamby** [comment]
> Confirmed, there is a bug when a mining units has never been started getting the ore pool of the map, I still have to investigate a bit more about what's going wrong with it, but i should be able to manage it.

Awesome thanks for the fast reply.

**Comment by thoda-dev** [comment]
@EricHamby Solved in the latest version.
