### ISSUE TITLE
a LITTLE CONFUSED

### ISSUE THREAD

**Issue by smooreace** [Jericho1060/DU-Mining-Units-Monitoring#3]
![image](https://github.com/Jericho1060/DU-Mining-Units-Monitoring/assets/35540547/08c7a26b-4455-4be3-91d1-9b07c6002d87)
These were all just calibrated. Why does it say one is due in 4 days and the others due in 3?

**Comment by thoda-dev** [comment]
Hi, it's due to the optimal calibration required. You have 3 that require 100% calibration to extract the maximum amount of ore, the last one only require 74% so it can be calibrated later.
